import { createGlobalTheme } from '@vanilla-extract/css';

import { base } from '../layers.css';
import { toFluidClampFor } from '../scale';

export const refs = createGlobalTheme(':root', {
  '@layer': base,

  colors: {
    neutral: {
      0: '#000000',
      10: '#161c1d',
      20: '#2c383a',
      30: '#435456',
      40: '#597173',
      50: '#6f8d90',
      60: '#8ca4a6',
      70: '#a9bbbc',
      80: '#c5d1d3',
      90: '#e2e8e9',
      100: '#ffffff',
    },
    primary: {
      0: '#000000',
      10: '#1a1110',
      20: '#401d10',
      30: '#7f3a1a',
      40: '#bf5b21',
      50: '#f27f1b',
      60: '#f2a950',
      70: '#e6bd8a',
      80: '#e4cebc',
      90: '#ece8e2',
      100: '#ffffff',
    },
  },

  typeface: {
    brand: 'serif',
    plain: 'sans-serif',
  },

  lineHeight: {
    md: '1',
    lg: '1.2',
    xl: '1.4',
  },

  spacing: {
    1: toFluidClampFor(4, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    2: toFluidClampFor(8, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    3: toFluidClampFor(12, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    4: toFluidClampFor(16, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    5: toFluidClampFor(20, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    6: toFluidClampFor(24, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    7: toFluidClampFor(28, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    8: toFluidClampFor(32, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    9: toFluidClampFor(36, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    10: toFluidClampFor(40, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    11: toFluidClampFor(44, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    12: toFluidClampFor(48, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    13: toFluidClampFor(52, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    14: toFluidClampFor(56, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    15: toFluidClampFor(60, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    16: toFluidClampFor(64, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    17: toFluidClampFor(68, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
    18: toFluidClampFor(72, {
      lowMin: 4,
      lowMax: 72,
      highMin: 6,
      highMax: 176,
      exponent: 2,
      rounding: 'none',
    }),
  },

  typeScale: {
    displayLarge: toFluidClampFor(40, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    displayMedium: toFluidClampFor(34, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    displaySmall: toFluidClampFor(28, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    headlineLarge: toFluidClampFor(32, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    headlineMedium: toFluidClampFor(28, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    headlineSmall: toFluidClampFor(24, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    titleLarge: toFluidClampFor(24, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    titleMedium: toFluidClampFor(18, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    titleSmall: toFluidClampFor(17, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    bodyLarge: toFluidClampFor(19, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    bodyMedium: toFluidClampFor(14, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    bodySmall: toFluidClampFor(12, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    labelLarge: toFluidClampFor(16, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    labelMedium: toFluidClampFor(14, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
    labelSmall: toFluidClampFor(12, {
      lowMin: 12,
      lowMax: 40,
      highMin: 14,
      highMax: 85,
      exponent: 2,
      rounding: 'none',
    }),
  },
});
